In [ ]:
# Numpy : 파이썬에서 수학과 데이터 분석을 쉽게 할 수 있도록 도와주는 라이브러리
# ndArray : 숫자를 여러 차원으로 저장할 수 있는 배열
# Numpy로 할 수 있는 것들
# - 숫자 묶음 생성
# - 평균, 합계, 최대값
# - 배열 덧셈, 곱셈
# - 2차원 표 (행렬)

# 일반 리스트

a = [1,2,3]
b = [4, 5, 6]

a+b



[1, 2, 3, 4, 5, 6]

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# numpy 수학용 배열, 모든 원소가 같은 타입

a+b

array([5, 7, 9])

In [4]:
import numpy as np

arr1 = np.array([1,2,3,4])

arr2 = ([1,2,3,4])

print(type(arr1))
print(type(arr2))


<class 'numpy.ndarray'>
<class 'list'>


In [5]:
# 2차원 ndArray 생성
# 1차원 배열 두개가 리스트로 묶은 형태

arr2 = np.array([[1,2,3,4],[5,6,7,8]])

arr3 = np.array([[[1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4]]])

print("2차원 배열")
print(arr2)

print("3차원 배열")
print(arr3)



2차원 배열
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [6]:
import numpy as np

a = np.array([1,2,3,4])

print(a+1)
print(a*2)
print(a**2)



[2 3 4 5]
[2 4 6 8]
[ 1  4  9 16]


In [14]:
import numpy as np

arr1 = np.array([1,2,3,4])

arr2 = np.array([[1,2,3,4],[5,6,7,8]])

arr3 = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])

# ndim : 배열의 차원 수

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

print(arr1.size)
print(arr2.size)
print(arr3.size)

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

# data : 배열의 실제 데이터가 저장된 메모리 버퍼

print(arr1.data)
print(arr2.data)
print(arr3.data)

arr = np.array([[1,2,3,4], [5,6,7,8]])

print("원래 배열")
print(arr)

print("전치 배열")
print(arr.T)



1
2
3
(4,)
(2, 4)
(2, 2, 4)
4
8
16
int64
int64
int64
8
8
8
원래 배열
[[1 2 3 4]
 [5 6 7 8]]
전치 배열
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [16]:
# ndArray.flatten()

print("원래 배열")
print(arr)

print("1차원으로 펼친 배열")
print(arr.flatten())

flat = arr.flatten()
flat[0] = 100

print("배열 출력")
print(arr)

원래 배열
[[1 2 3 4]
 [5 6 7 8]]
1차원으로 펼친 배열
[1 2 3 4 5 6 7 8]
배열 출력
[[1 2 3 4]
 [5 6 7 8]]


In [19]:
# ndarray.reshape()

arr = np.array([1,2,3,4,5,6])

print("원래 배열")
print(arr)

arr2 = arr.reshape(2,3)
print("reshape 배열")
print(arr2)


원래 배열
[1 2 3 4 5 6]
reshape 배열
[[1 2 3]
 [4 5 6]]


In [ ]:
# ndArray.sum()
# axis : 어느 축을 기준으로 계산할 것인가
# axis 옵션
# axis = 0 열 -> (세로 축) 방향 합
# axis = 1 열 -> (가로 축) 방향 합

arr = np.array([[1,2,3], [4,5,6]])
0
print("전체합 :", arr.sum())

print("열 방향 합(axis=0:)", arr.sum(axis=0))
print("행 방향 합(axis=1:)", arr.sum(axis=1))


arr = np.array([[1,2,3], [4,5,6]])

print("전체 평균:", arr.mean())

print("열 방향 평균 (axis=0) :", arr.mean(axis=0))
print("행 방향 평균 (axis=1) :", arr.mean(axis=1))







전체합 : 21
열 방향 합(axis=0:) [5 7 9]
행 방향 합(axis=1:) [ 6 15]
전체 평균: 3.5
열 방향 평균 (axis=0) : [2.5 3.5 4.5]
행 방향 평균 (axis=1) : [2. 5.]


In [25]:

arr = np.array([[1,2,3], [4,5,6]])

print("전체 최솟값 :", arr.min())
print("전체 최대값 :", arr.max())

print("열 방향 최솟값 axis=0 :", arr.min(axis=0))
print("행 방향 최솟값 axis=1 :", arr.min(axis=1))

print("열 방향 최대값 axis=0 :", arr.max(axis=0))
print("행 방향 최대값 axis=1 :", arr.max(axis=1))


전체 최솟값 : 1
전체 최대값 : 6
열 방향 최솟값 axis=0 : [1 2 3]
행 방향 최솟값 axis=1 : [1 4]
열 방향 최대값 axis=0 : [4 5 6]
행 방향 최대값 axis=1 : [3 6]


In [ ]:
print("--- Zero Like ---")
print(np.zeros_like(arr2))  # (1) 출력

print("\n--- Full Like ---") # (2) 한 칸 띄우고 출력
print(np.full_like(arr2, 7))

print("\n--- One Like ---")  # (3) 또 한 칸 띄우고 출력
print(np.ones_like(arr2))

In [65]:
import numpy as np

np.random.randint(-100, 100, (2,3))



array([[-11, -43,  13],
       [ 11, -17, -60]], dtype=int32)

In [84]:
import numpy as np

# 1번 시드 결과
np.random.seed(1)
print("Seed 1 result:\n", np.random.randint(0, 10, (2,3)))

# 2번 시드 결과
np.random.seed(2)
print("\nSeed 2 result:\n", np.random.randint(0, 10, (2,3)))

Seed 1 result:
 [[5 8 9]
 [5 0 0]]

Seed 2 result:
 [[8 8 6]
 [2 8 7]]


In [93]:
import numpy as np

arr1 = np.array([1,2,3,4])

arr2 = np.array([[1,2,3,4], [5,6,7,8]])

print("파이썬 기본 리스트 예시")
li = [1,2,3,4]

print(li[0])

print("1차원 배열 인덱싱")
print(arr1[0])

print("1차원 배열 슬라이싱")
print(arr1[1:3:])

print(arr2[1,2])

print(arr2[1:2, 1:3])

print("1차원 배열 fancy 인덱싱")
print(arr1[[0,1,3]])

print("2차원 배열 fancy 인덱싱")
print(arr2[[0,1], [1,3]])

파이썬 기본 리스트 예시
1
1차원 배열 인덱싱
1
1차원 배열 슬라이싱
[2 3]
7
[[6 7]]
1차원 배열 fancy 인덱싱
[1 2 4]
2차원 배열 fancy 인덱싱
[2 8]


In [ ]:
np.zeros((3,4))

np.ones((2,3,4))


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])